// Build the Webhost AI marketing site to apps/marketing/dist/.
// Dogfoods @webhost/generator: our own landing page is a generated site, and
// the /demos/ gallery showcases real generated small-business sites — the same
// output the outreach tool will send to prospects.
// Node strips the TypeScript types from the imported .ts source at runtime.
import { generateSite } from "../../packages/generator/src/index.ts";
import { runCampaign } from "../../packages/outreach/src/index.ts";
import { mkdir, writeFile, readFile, readdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const outDir = join(here, "dist");
const samplesDir = join(repoRoot, "samples");
const leadsFile = join(repoRoot, "packages", "outreach", "leads", "sample-leads.json");
// Public base URL the demos are served from (the GitHub Pages site).
const PAGES_BASE_URL = "https://fossamalaent.github.io/webhost-ai";

// --- Our own landing page (dogfooded through the generator) -----------------

const company = {
  name: "Webhost AI",
  industry: "Websites with hosting included",
  location: "Online — serving small businesses everywhere",
  tagline:
    "We build your small-business website and host it for you — see it live before you pay.",
  about:
    "Webhost AI designs, builds, and hosts professional websites for small businesses. " +
    "No setup headaches, no separate hosting bill, no agency retainer — one simple package. " +
    "We even generate a free preview of your future site so you can see it before you commit.",
  brandColor: "#0b6e4f",
  template: "bold",
  ctaLabel: "Get my free preview",
  heroImage: {
    src: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=1600&q=80",
    alt: "A small-business owner working on a laptop",
  },
  services: [
    { name: "Done-for-you website", description: "A clean, fast, mobile-friendly site built from your business details.", price: "Included" },
    { name: "Hosting included", description: "Reliable hosting, SSL, and a custom domain — all handled for you.", price: "No extra bill" },
    { name: "Free preview", description: "See a real demo of your site before you pay a cent.", price: "Free" },
  ],
  testimonials: [
    { quote: "I had a real, live website the same week — and I never touched a line of code.", author: "Small-business owner" },
  ],
  contact: { email: "hello@webhost.ai" },
};

// --- Demo gallery from samples/ --------------------------------------------

async function loadSamples() {
  let files = [];
  try {
    files = (await readdir(samplesDir)).filter((f) => f.endsWith(".json"));
  } catch {
    return [];
  }
  const demos = [];
  for (const file of files.sort()) {
    const raw = await readFile(join(samplesDir, file), "utf8");
    const business = JSON.parse(raw);
    const site = generateSite(business);
    demos.push({ business, site });
  }
  return demos;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function galleryPage(demos) {
  const cards = demos
    .map((d) => {
      const b = d.business;
      const thumb = b.heroImage?.src ?? "";
      const thumbHtml = thumb
        ? `<img src="${escapeHtml(thumb)}" alt="${escapeHtml(b.name)} website preview" loading="lazy" />`
        : "";
      return `      <a class="demo" href="./${escapeHtml(d.site.slug)}/">
        ${thumbHtml}
        <div class="meta">
          <h2>${escapeHtml(b.name)}</h2>
          <p>${escapeHtml(b.industry)} &middot; ${escapeHtml(b.location)}</p>
          <span class="tag">${escapeHtml(d.site.template)} template</span>
        </div>
      </a>`;
    })
    .join("\n");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Webhost AI — Live demo sites</title>
  <meta name="description" content="Real small-business websites generated by Webhost AI." />
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1a1a1a; background: #f5f6f5; line-height: 1.6; }
    .wrap { max-width: 1040px; margin: 0 auto; padding: 0 24px; }
    header { background: #0f1115; color: #fff; padding: 64px 0; text-align: center; }
    header h1 { font-size: clamp(2rem, 5vw, 3rem); margin: 0 0 12px; }
    header p { opacity: 0.85; margin: 0 auto; max-width: 560px; }
    header a { color: #6ee7b7; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 22px; padding: 48px 0; }
    .demo { display: block; background: #fff; border-radius: 16px; overflow: hidden; text-decoration: none; color: inherit; border: 1px solid #e6e8e6; transition: transform 0.12s ease, box-shadow 0.12s ease; }
    .demo:hover { transform: translateY(-3px); box-shadow: 0 12px 30px rgba(0,0,0,0.10); }
    .demo img { width: 100%; height: 190px; object-fit: cover; display: block; }
    .demo .meta { padding: 20px 22px; }
    .demo h2 { margin: 0 0 6px; font-size: 1.25rem; }
    .demo .meta p { margin: 0 0 12px; color: #5a5a5a; }
    .tag { display: inline-block; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em; font-weight: 600; color: #0b6e4f; background: #e7f3ee; padding: 4px 10px; border-radius: 999px; }
    footer { text-align: center; padding: 40px 0 60px; color: #5a5a5a; font-size: 0.9rem; }
    footer a { color: #0b6e4f; }
  </style>
</head>
<body>
  <header>
    <div class="wrap">
      <h1>Live demo sites</h1>
      <p>Each of these was generated from a few lines of business details by <a href="../">Webhost AI</a> — the same output a prospect receives in their outreach preview.</p>
    </div>
  </header>
  <main class="wrap">
    <div class="grid">
${cards}
    </div>
  </main>
  <footer>
    <p>Generated by <a href="../">Webhost AI</a>. Website &amp; hosting included.</p>
  </footer>
</body>
</html>
`;
}

// --- Build ------------------------------------------------------------------

await mkdir(outDir, { recursive: true });

const { html: homeHtml } = generateSite(company);
await writeFile(join(outDir, "index.html"), homeHtml, "utf8");
// .nojekyll keeps GitHub Pages from mangling paths and speeds publishing.
await writeFile(join(outDir, ".nojekyll"), "", "utf8");
console.log(`Built marketing home -> index.html (${homeHtml.length} bytes)`);

const demos = await loadSamples();
for (const d of demos) {
  const dir = join(outDir, "demos", d.site.slug);
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "index.html"), d.site.html, "utf8");
  console.log(`Built demo -> demos/${d.site.slug}/index.html (${d.site.bytes} bytes, ${d.site.template})`);
}

if (demos.length) {
  await mkdir(join(outDir, "demos"), { recursive: true });
  await writeFile(join(outDir, "demos", "index.html"), galleryPage(demos), "utf8");
  console.log(`Built demo gallery -> demos/index.html (${demos.length} demos)`);
}

// --- Outreach prospect demos ------------------------------------------------
// Render the live preview demos the outreach tool links in its messages, so the
// preview URLs in any campaign sheet resolve to real pages on this deploy. These
// are reachable by URL (for the prospect) but kept out of the public gallery.

async function buildOutreachDemos() {
  let leads = [];
  try {
    const parsed = JSON.parse(await readFile(leadsFile, "utf8"));
    leads = Array.isArray(parsed) ? parsed : parsed.leads ?? [];
  } catch {
    return;
  }
  if (!leads.length) return;

  const campaign = runCampaign(leads, { baseUrl: PAGES_BASE_URL });
  for (const r of campaign.results) {
    const dir = join(outDir, "demos", r.slug);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "index.html"), r.html, "utf8");
    console.log(`Built outreach demo -> demos/${r.slug}/index.html  (${r.previewUrl})`);
  }
  if (campaign.errors.length) {
    for (const e of campaign.errors) {
      console.error(`  ! outreach lead "${e.lead.name || "(unnamed)"}" failed: ${e.error}`);
    }
  }
}

await buildOutreachDemos();
